version: '3.9'

services:

  redis:
    build: ./redis
    container_name: redis
    volumes:
      - ./redis/data:/data
      - ./redis/config/redis.conf:/usr/local/etc/redis/redis.conf:ro
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 5s
    ports:
      - "6379:6379"
    networks:
      - c46-net

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: booking
      POSTGRES_MAX_CONNECTIONS: 300
    volumes:
      - pgdata:/var/lib/postgresql/data
      # - ./data/postgres:/var/lib/postgresql/data:delegated
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U booking" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    networks:
      - c46-net

  axon-server:
    image: axoniq/axonserver:2024.1.1
    container_name: axon-server
    restart: always
    environment:
      - AXONIQ_AXONSERVER_CONTEXTS=default

      - AXONIQ_AXONSERVER_AUTOCLUSTER_FIRST=axonserver
      - AXONIQ_AXONSERVER_AUTOCLUSTER_CONTEXTS=default

      - AXONIQ_AXONSERVER_DEVMODE_ENABLED=true

      - AXONIQ_AXONSERVER_NAME=axonserver
      - AXONIQ_AXONSERVER_HOSTNAME=axonserver
    ports:
      - "8024:8024" # dashboard
      - "8124:8124" # grpc
      - "8224:8224" # Internal cluster
    volumes:
      - axon-data:/axonserver/data
      - axon-events:/axonserver/events
      - axon-config:/axonserver/config

    # volumes:
    #   - ./data/axon/data:/axonserver/data
    #   - ./data/axon/events:/axonserver/events
    #   - ./data/axon/config:/axonserver/config
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:8024" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - c46-net

  api-gateway:
    build: ./ApiGateway
    container_name: api-gateway
    restart: always
    depends_on:
      - auth-service
      - booking-service
      - notification-service
      - patient-service
      - staff-service
      - medical-package-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xmx512m -Xms256m
      - TZ=Asia/Ho_Chi_Minh
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:8080/actuator/health" ]
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - c46-net

  booking-service:
    build: ./BookingService
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      axon-server:
        condition: service_healthy
    ports:
      - "8082:8082"
    environment:
      - AXON_AXONSERVER_SERVERS=axon-server
      - AXONSERVER_HOST=axon-server
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/booking_db
      - SPRING_DATASOURCE_USERNAME=booking
      - SPRING_DATASOURCE_PASSWORD=booking
      - JAVA_OPTS=-Xmx512m -Xms256m
      - TZ=Asia/Ho_Chi_Minh
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:8082/actuator/health" ]
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - c46-net
  auth-service:
    build: ./AuthService
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      axon-server:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      - PUBLIC_BASE_URL=http://localhost:3000

      - AXON_AXONSERVER_SERVERS=axon-server
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/auth_db
      - SPRING_DATASOURCE_USERNAME=booking
      - SPRING_DATASOURCE_PASSWORD=booking
      - JAVA_OPTS=-Xmx512m -Xms256m
      - TZ=Asia/Ho_Chi_Minh
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:8081/actuator/health" ]
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - c46-net

  notification-service:
    build: ./NotificationService
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      axon-server:
        condition: service_healthy
    environment:
      - MAIL_HOST=smtp.gmail.com
      - MAIL_PORT=587
      # - MAIL_USERNAME=${MAIL_USERNAME}
      # - MAIL_PASSWORD=${MAIL_PASSWORD} 
      # - SPRING_PROFILES_ACTIVE=prod # kích hoạt profile tương ứng -> load cấu hình khác nhau

      - AXON_AXONSERVER_SERVERS=axon-server
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/auth_db
      - SPRING_DATASOURCE_USERNAME=booking
      - SPRING_DATASOURCE_PASSWORD=booking
      - JAVA_OPTS=-Xmx512m -Xms256m
      - TZ=Asia/Ho_Chi_Minh
    env_file:
      - .env
    ports:
      - "8083:8080"
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:8081/actuator/health" ]
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - c46-net
  patient-service:
    build: ./PatientService
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      axon-server:
        condition: service_healthy
    ports:
      - "8088:8088"
    environment:
      - AXON_AXONSERVER_SERVERS=axon-server
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/patient_db
      - SPRING_DATASOURCE_USERNAME=booking
      - SPRING_DATASOURCE_PASSWORD=booking
      - JAVA_OPTS=-Xmx512m -Xms256m
      - TZ=Asia/Ho_Chi_Minh
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:8088/actuator/health" ]
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - c46-net

  staff-service:
    build: ./StaffService
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      axon-server:
        condition: service_healthy
    ports:
      - "8090:8090"
    environment:
      - AXON_AXONSERVER_SERVERS=axon-server
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/staff_db
      - SPRING_DATASOURCE_USERNAME=booking
      - SPRING_DATASOURCE_PASSWORD=booking
      - JAVA_OPTS=-Xmx512m -Xms256m
      - TZ=Asia/Ho_Chi_Minh
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:8090/actuator/health" ]
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - c46-net
  medical-package-service:
    build: ./MedicalPackageService
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      axon-server:
        condition: service_healthy
    ports:
      - "8086:8086"
    environment:
      - AXON_AXONSERVER_SERVERS=axon-server
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/medical_package_db
      - SPRING_DATASOURCE_USERNAME=booking
      - SPRING_DATASOURCE_PASSWORD=booking
      - JAVA_OPTS=-Xmx512m -Xms256m
      - TZ=Asia/Ho_Chi_Minh
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:8086/actuator/health" ]
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - c46-net

  examination-service:
    build: ./ExaminationService
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      axon-server:
        condition: service_healthy
    ports:
      - "9094:9094"
    environment:
      - AXON_AXONSERVER_SERVERS=axon-server
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/examination_db
      - SPRING_DATASOURCE_USERNAME=booking
      - SPRING_DATASOURCE_PASSWORD=booking
      - JAVA_OPTS=-Xmx512m -Xms256m
      - TZ=Asia/Ho_Chi_Minh
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:9094/actuator/health" ]
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - c46-net
  examination-flow-service:
    build: ./ExaminationFlowService
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      axon-server:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "9093:9093"
    environment:
      - AXON_AXONSERVER_SERVERS=axon-server
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/examination_flow_db
      - SPRING_DATASOURCE_USERNAME=booking
      - SPRING_DATASOURCE_PASSWORD=booking
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - JAVA_OPTS=-Xmx512m -Xms256m
      - TZ=Asia/Ho_Chi_Minh
    healthcheck:
      test: [ "CMD", "wget", "--spider", "http://localhost:9093/actuator/health" ]
      interval: 20s
      timeout: 10s
      retries: 5
    networks:
      - c46-net

  python-server:
    image: python:3.11-alpine
    container_name: html-python-server
    ports:
      - "9999:9999"
    working_dir: /app
    volumes:
      - ./html:/app
    command: >
      sh -c "cd /app && 
             python -m http.server 9999"
    networks:
      - c46-net

volumes:
  pgdata:
  axon-data:
  axon-events:
  axon-config:


networks:
  c46-net:
    driver: bridge
